print("Bienvenido al generador de nombre de banda!.\nCual es el nombre de la ciudad en donde naciste?")
nameCity = input()
print("Cual es el nombre de tu mascota?")
namePet = input()
print("El nombre de tu banda podria ser: " + " '" + nameCity + " " + namePet + "'" )